[".local/share/nvim/site/autoload/plug.vim"]
    type = "file"
    url = "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    refreshPeriod = "168h"
[".local/pdf/apa.csl"]
    type = "file"
    url = "https://www.zotero.org/styles/apa"
