If:
  PathMatch: [.*\.c, .*\.h]
CompileFlags:
  Add: [-xc, -Wall, -Wextra]
---
If:
  PathMatch: [.*\.cpp, .*\.cc, .*\.hpp, .*\.hh]
CompileFlags:
  Add: [-xc++, -Wall, -Wextra, -Wno-unused-const-variable]
---
If:
  PathMatch: [.*\.h, .*\.hpp, .*\.hh]
CompileFlags:
  Add: [-Wno-unused-function]
