If:
  PathExclude: [.*\.c, .*\.h]
CompileFlags:
  Add: [-xc++, -std=c++23, -Wall, -Wno-unused-const-variable]
---
If:
  PathExclude: [.*\.cpp, .*\.hpp]
CompileFlags:
  Add: [-xc, -std=gnu11, -Wall, -Wextra]
