If:
  PathMatch: [.*\.c, .*\.h]
CompileFlags:
  Add: [-xc, -std=c11, -Wall, -Wextra]
---
If:
  PathMatch: [.*\.cpp, .*\.hpp]
CompileFlags:
  Add: [-xc++, -std=c++23, -Wall, -Wextra, -Wno-unused-const-variable]
